from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

aq_lcd_grab = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'Conn_01x39_Socket', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x39_Socket'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'FH26W:FH26W39S03SHW60', 'keywords':'connector', 'description':'Generic connector, single row, 01x39, script generated', 'datasheet':'', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='Pin_3',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='Pin_4',func=pin_types.PASSIVE,unit=1),
            Pin(num='5',name='Pin_5',func=pin_types.PASSIVE,unit=1),
            Pin(num='6',name='Pin_6',func=pin_types.PASSIVE,unit=1),
            Pin(num='7',name='Pin_7',func=pin_types.PASSIVE,unit=1),
            Pin(num='8',name='Pin_8',func=pin_types.PASSIVE,unit=1),
            Pin(num='9',name='Pin_9',func=pin_types.PASSIVE,unit=1),
            Pin(num='10',name='Pin_10',func=pin_types.PASSIVE,unit=1),
            Pin(num='11',name='Pin_11',func=pin_types.PASSIVE,unit=1),
            Pin(num='12',name='Pin_12',func=pin_types.PASSIVE,unit=1),
            Pin(num='13',name='Pin_13',func=pin_types.PASSIVE,unit=1),
            Pin(num='14',name='Pin_14',func=pin_types.PASSIVE,unit=1),
            Pin(num='15',name='Pin_15',func=pin_types.PASSIVE,unit=1),
            Pin(num='16',name='Pin_16',func=pin_types.PASSIVE,unit=1),
            Pin(num='17',name='Pin_17',func=pin_types.PASSIVE,unit=1),
            Pin(num='18',name='Pin_18',func=pin_types.PASSIVE,unit=1),
            Pin(num='19',name='Pin_19',func=pin_types.PASSIVE,unit=1),
            Pin(num='20',name='Pin_20',func=pin_types.PASSIVE,unit=1),
            Pin(num='21',name='Pin_21',func=pin_types.PASSIVE,unit=1),
            Pin(num='22',name='Pin_22',func=pin_types.PASSIVE,unit=1),
            Pin(num='23',name='Pin_23',func=pin_types.PASSIVE,unit=1),
            Pin(num='24',name='Pin_24',func=pin_types.PASSIVE,unit=1),
            Pin(num='25',name='Pin_25',func=pin_types.PASSIVE,unit=1),
            Pin(num='26',name='Pin_26',func=pin_types.PASSIVE,unit=1),
            Pin(num='27',name='Pin_27',func=pin_types.PASSIVE,unit=1),
            Pin(num='28',name='Pin_28',func=pin_types.PASSIVE,unit=1),
            Pin(num='29',name='Pin_29',func=pin_types.PASSIVE,unit=1),
            Pin(num='30',name='Pin_30',func=pin_types.PASSIVE,unit=1),
            Pin(num='31',name='Pin_31',func=pin_types.PASSIVE,unit=1),
            Pin(num='32',name='Pin_32',func=pin_types.PASSIVE,unit=1),
            Pin(num='33',name='Pin_33',func=pin_types.PASSIVE,unit=1),
            Pin(num='34',name='Pin_34',func=pin_types.PASSIVE,unit=1),
            Pin(num='35',name='Pin_35',func=pin_types.PASSIVE,unit=1),
            Pin(num='36',name='Pin_36',func=pin_types.PASSIVE,unit=1),
            Pin(num='37',name='Pin_37',func=pin_types.PASSIVE,unit=1),
            Pin(num='38',name='Pin_38',func=pin_types.PASSIVE,unit=1),
            Pin(num='39',name='Pin_39',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_01x03_Socket', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x03_Socket'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_PinHeader_2.54mm:PinHeader_1x03_P2.54mm_Vertical', 'keywords':'connector', 'description':'Generic connector, single row, 01x03, script generated', 'datasheet':'', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='Pin_3',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_01x04_Socket', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x04_Socket'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_PinHeader_2.54mm:PinHeader_1x04_P2.54mm_Vertical', 'keywords':'connector', 'description':'Generic connector, single row, 01x04, script generated', 'datasheet':'', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='Pin_3',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='Pin_4',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R'}), 'ref_prefix':'R', 'fplist':[''], 'footprint':'Resistor_SMD:R_0402_1005Metric', 'keywords':'R res resistor', 'description':'Resistor', 'datasheet':'', 'pins':[
            Pin(num='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'RP2350_60QFN', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'RP2350_60QFN'}), 'ref_prefix':'U', 'fplist':['RP2350_60QFN_minimal:RP2350-QFN-60-1EP_7x7_P0.4mm_EP3.4x3.4mm_ThermalVias'], 'footprint':'RP2350_60QFN_minimal:RP2350-QFN-60-1EP_7x7_P0.4mm_EP3.4x3.4mm_ThermalVias', 'keywords':'', 'description':'', 'datasheet':'', 'pins':[
            Pin(num='1',name='IOVDD',func=pin_types.PWRIN,unit=1),
            Pin(num='10',name='GPIO7',func=pin_types.BIDIR,unit=1),
            Pin(num='11',name='IOVDD',func=pin_types.PWRIN,unit=1),
            Pin(num='12',name='GPIO8',func=pin_types.BIDIR,unit=1),
            Pin(num='13',name='GPIO9',func=pin_types.BIDIR,unit=1),
            Pin(num='14',name='GPIO10',func=pin_types.BIDIR,unit=1),
            Pin(num='15',name='GPIO11',func=pin_types.BIDIR,unit=1),
            Pin(num='16',name='GPIO12',func=pin_types.BIDIR,unit=1),
            Pin(num='17',name='GPIO13',func=pin_types.BIDIR,unit=1),
            Pin(num='18',name='GPIO14',func=pin_types.BIDIR,unit=1),
            Pin(num='19',name='GPIO15',func=pin_types.BIDIR,unit=1),
            Pin(num='2',name='GPIO0',func=pin_types.BIDIR,unit=1),
            Pin(num='20',name='IOVDD',func=pin_types.PWRIN,unit=1),
            Pin(num='21',name='XIN',func=pin_types.INPUT,unit=1),
            Pin(num='22',name='XOUT',func=pin_types.PASSIVE,unit=1),
            Pin(num='23',name='DVDD',func=pin_types.PWRIN,unit=1),
            Pin(num='24',name='SWCLK',func=pin_types.OUTPUT,unit=1),
            Pin(num='25',name='SWD',func=pin_types.BIDIR,unit=1),
            Pin(num='26',name='RUN',func=pin_types.INPUT,unit=1),
            Pin(num='27',name='GPIO16',func=pin_types.BIDIR,unit=1),
            Pin(num='28',name='GPIO17',func=pin_types.BIDIR,unit=1),
            Pin(num='29',name='GPIO18',func=pin_types.BIDIR,unit=1),
            Pin(num='3',name='GPIO1',func=pin_types.BIDIR,unit=1),
            Pin(num='30',name='IOVDD',func=pin_types.PWRIN,unit=1),
            Pin(num='31',name='GPIO19',func=pin_types.BIDIR,unit=1),
            Pin(num='32',name='GPIO20',func=pin_types.BIDIR,unit=1),
            Pin(num='33',name='GPIO21',func=pin_types.BIDIR,unit=1),
            Pin(num='34',name='GPIO22',func=pin_types.BIDIR,unit=1),
            Pin(num='35',name='GPIO23',func=pin_types.BIDIR,unit=1),
            Pin(num='36',name='GPIO24',func=pin_types.BIDIR,unit=1),
            Pin(num='37',name='GPIO25',func=pin_types.BIDIR,unit=1),
            Pin(num='38',name='IOVDD',func=pin_types.PWRIN,unit=1),
            Pin(num='39',name='DVDD',func=pin_types.PWRIN,unit=1),
            Pin(num='4',name='GPIO2',func=pin_types.BIDIR,unit=1),
            Pin(num='40',name='GPIO26_ADC0',func=pin_types.BIDIR,unit=1),
            Pin(num='41',name='GPIO27_ADC1',func=pin_types.BIDIR,unit=1),
            Pin(num='42',name='GPIO28_ADC2',func=pin_types.BIDIR,unit=1),
            Pin(num='43',name='GPIO29_ADC3',func=pin_types.BIDIR,unit=1),
            Pin(num='44',name='ADC_AVDD',func=pin_types.PWRIN,unit=1),
            Pin(num='45',name='IOVDD',func=pin_types.PWRIN,unit=1),
            Pin(num='46',name='VREG_AVDD',func=pin_types.PWRIN,unit=1),
            Pin(num='47',name='VREG_PGND',func=pin_types.PWRIN,unit=1),
            Pin(num='48',name='VREG_LX',func=pin_types.PWROUT,unit=1),
            Pin(num='49',name='VREG_VIN',func=pin_types.PWRIN,unit=1),
            Pin(num='5',name='GPIO3',func=pin_types.BIDIR,unit=1),
            Pin(num='50',name='VREG_FB',func=pin_types.INPUT,unit=1),
            Pin(num='51',name='USB_DM',func=pin_types.BIDIR,unit=1),
            Pin(num='52',name='USB_DP',func=pin_types.BIDIR,unit=1),
            Pin(num='53',name='USB_OTP_VDD',func=pin_types.PWRIN,unit=1),
            Pin(num='54',name='QSPI_IOVDD',func=pin_types.PWRIN,unit=1),
            Pin(num='55',name='QSPI_SD3',func=pin_types.BIDIR,unit=1),
            Pin(num='56',name='QSPI_SCLK',func=pin_types.OUTPUT,unit=1),
            Pin(num='57',name='QSPI_SD0',func=pin_types.BIDIR,unit=1),
            Pin(num='58',name='QSPI_SD2',func=pin_types.BIDIR,unit=1),
            Pin(num='59',name='QSPI_SD1',func=pin_types.BIDIR,unit=1),
            Pin(num='6',name='DVDD',func=pin_types.PWRIN,unit=1),
            Pin(num='60',name='QSPI_SS',func=pin_types.BIDIR,unit=1),
            Pin(num='61',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='7',name='GPIO4',func=pin_types.BIDIR,unit=1),
            Pin(num='8',name='GPIO5',func=pin_types.BIDIR,unit=1),
            Pin(num='9',name='GPIO6',func=pin_types.BIDIR,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'C', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C'}), 'ref_prefix':'C', 'fplist':[''], 'footprint':'Capacitor_SMD:C_0402_1005Metric', 'keywords':'cap capacitor', 'description':'Unpolarized capacitor', 'datasheet':'', 'pins':[
            Pin(num='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'L', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'L'}), 'ref_prefix':'L', 'fplist':[''], 'footprint':'RP2350_60QFN_minimal:L_pol_2016', 'keywords':'inductor choke coil reactor magnetic', 'description':'Inductor', 'datasheet':'', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Crystal_GND24', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Crystal_GND24'}), 'ref_prefix':'Y', 'fplist':[''], 'footprint':'Crystal:Crystal_SMD_3225-4Pin_3.2x2.5mm', 'keywords':'quartz ceramic resonator oscillator', 'description':'Four pin crystal, GND on pins 2 and 4', 'datasheet':'', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='G',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='3',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='G',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_01x03_Pin', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x03_Pin'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_PinHeader_2.54mm:PinHeader_1x03_P2.54mm_Vertical', 'keywords':'connector', 'description':'Generic connector, single row, 01x03, script generated', 'datasheet':'', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='Pin_3',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'LED', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LED'}), 'ref_prefix':'D', 'fplist':[''], 'footprint':'LED_SMD:LED_0603_1608Metric', 'keywords':'LED diode', 'description':'Light emitting diode', 'datasheet':'', 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='A',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'TestPoint', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TestPoint'}), 'ref_prefix':'TP', 'fplist':[''], 'footprint':'TestPoint:TestPoint_Pad_1.0x1.0mm', 'keywords':'test point tp', 'description':'test point', 'datasheet':'', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] })])