//! Bake `templates/<W>x<H>/<label>.png` into a hash table the decoder
//! can match against at runtime, and emit bitmasks for unit tests.
//!
//! Each template PNG is binarized (any non-black pixel = foreground).
//! The hash is FNV-1a 64-bit over the RLE run-length sequence of the
//! binarized pixel stream, iterated in reverse (display orientation —
//! same convention as the runtime accumulator in decoder.rs).
//!
//! Outputs in `$OUT_DIR/`:
//!
//! `templates_gen.rs` — runtime match table:
//! ```ignore
//! pub struct Template { pub w: u16, pub h: u16, pub label: &'static str, pub hash: u64 }
//! pub static TEMPLATES: &[Template] = &[ ... ];
//! ```
//!
//! `test_pixels_gen.rs` — per-template packed-bit masks for unit tests:
//! ```ignore
//! // Bits in capture order (reversed from PNG/display order).
//! // Bit i set → pixel i is foreground. The test chooses any bg/fg RGB565 pair.
//! pub static TEST_MASK_40x61_0: &[u8] = &[...];
//! // ... one constant per template ...
//! ```
//!
//! A build-time assertion checks that no two templates of the same
//! size share a hash.

use std::path::{Path, PathBuf};

include!("src/fnv.rs");

fn main() {
    let dir = PathBuf::from("templates");
    println!("cargo:rerun-if-changed={}", dir.display());
    println!("cargo:rerun-if-changed=src/fnv.rs");

    // (w, h, label, hash, mask_in_capture_order)
    let mut entries: Vec<(u16, u16, String, u64, Vec<u8>)> = Vec::new();

    let size_dirs = std::fs::read_dir(&dir).expect("templates/ missing");
    for entry in size_dirs {
        let entry = entry.expect("read templates entry");
        let size_path = entry.path();
        if !size_path.is_dir() {
            continue;
        }
        let size_name = size_path
            .file_name()
            .and_then(|s| s.to_str())
            .expect("utf8 size name");
        let (w, h) = parse_size(size_name)
            .unwrap_or_else(|| panic!("bad size dir name {size_name:?} (expected WxH)"));
        println!("cargo:rerun-if-changed={}", size_path.display());

        for file in std::fs::read_dir(&size_path).expect("read size dir") {
            let file = file.expect("read entry");
            let path = file.path();
            if path.extension().and_then(|s| s.to_str()) != Some("png") {
                continue;
            }
            let stem = path
                .file_stem()
                .and_then(|s| s.to_str())
                .expect("utf8 stem")
                .to_string();
            println!("cargo:rerun-if-changed={}", path.display());
            let (hash, mask) = load_png(&path, w, h);
            entries.push((w, h, stem, hash, mask));
        }
    }

    entries.sort_by(|a, b| (a.0, a.1, &a.2).cmp(&(b.0, b.1, &b.2)));

    // Verify no two templates of the same size share a hash.
    for i in 0..entries.len() {
        for j in (i + 1)..entries.len() {
            let (wi, hi, li, hi_hash, _) = &entries[i];
            let (wj, hj, lj, hj_hash, _) = &entries[j];
            if wi == wj && hi == hj && hi_hash == hj_hash {
                panic!(
                    "hash collision: {li:?} and {lj:?} at {wi}x{hi} share hash {hi_hash:#018x}"
                );
            }
        }
    }

    let out_dir = std::env::var_os("OUT_DIR").expect("OUT_DIR");

    // --- templates_gen.rs ---
    let mut src = String::new();
    src.push_str("pub struct Template { pub w: u16, pub h: u16, pub label: &'static str, pub hash: u64 }\n");
    src.push_str("pub static TEMPLATES: &[Template] = &[\n");
    for (w, h, label, hash, _) in &entries {
        src.push_str(&format!(
            "    Template {{ w: {w}, h: {h}, label: {label:?}, hash: {hash:#018x} }},\n"
        ));
    }
    src.push_str("];\n");
    std::fs::write(Path::new(&out_dir).join("templates_gen.rs"), src)
        .expect("write templates_gen.rs");

    // --- test_pixels_gen.rs ---
    // Packed-bit masks in capture order (reverse of PNG/display order).
    // Bit i of byte i/8 is set when pixel i is foreground.
    // Tests may use any RGB565 bg/fg pair they like.
    let mut src = String::new();
    src.push_str("// Auto-generated by build.rs. Do not edit.\n");
    src.push_str("// Packed-bit masks in capture order (reverse of PNG/display order).\n");
    src.push_str("// Bit i set → pixel i is foreground. Tests choose any RGB565 bg/fg pair.\n");
    for (w, h, label, _, mask) in &entries {
        let const_name = label_to_ident(label);
        src.push_str(&format!(
            "#[allow(dead_code)]\npub static TEST_MASK_{w}X{h}_{const_name}: &[u8] = &{mask:?};\n"
        ));
    }
    std::fs::write(Path::new(&out_dir).join("test_pixels_gen.rs"), src)
        .expect("write test_pixels_gen.rs");
}

fn parse_size(s: &str) -> Option<(u16, u16)> {
    let (w, h) = s.split_once('x')?;
    Some((w.parse().ok()?, h.parse().ok()?))
}

fn label_to_ident(label: &str) -> String {
    match label {
        "blank" => "BLANK".into(),
        "dot"   => "DOT".into(),
        s       => s.to_uppercase(),
    }
}

/// Load a template PNG. Returns `(hash, mask)` where `mask` is a packed-bit
/// array in capture order (reversed from PNG image order). Bit i is set when
/// pixel i is foreground. Hash is FNV-1a over the RLE of that bit stream.
fn load_png(path: &Path, expected_w: u16, expected_h: u16) -> (u64, Vec<u8>) {
    let img = image::open(path).unwrap_or_else(|e| panic!("open {}: {e}", path.display()));
    let img = img.to_luma8();
    let (w, h) = (img.width() as u16, img.height() as u16);
    assert_eq!(
        (w, h),
        (expected_w, expected_h),
        "{}: dim {w}x{h} != dir {expected_w}x{expected_h}",
        path.display()
    );

    let n = w as usize * h as usize;
    // Binarize in display order, then build packed mask in capture order
    // (reverse). Bit i corresponds to pixel i in capture order.
    let display: Vec<bool> = img.pixels().map(|px| px.0[0] != 0).collect();
    let mut mask = vec![0u8; n.div_ceil(8)];
    for (i, &fg) in display.iter().rev().enumerate() {
        if fg {
            mask[i / 8] |= 1 << (i % 8);
        }
    }

    if n == 0 {
        return (FNV_OFFSET, mask);
    }

    // Hash in capture order. bg = pixel 0 in capture order = last in display.
    // Must match PendingWindow::push() in decoder.rs exactly.
    let bg = display[n - 1]; // capture order pixel 0
    let mut hash = FNV_OFFSET;
    let mut run_len: u16 = 1;
    let mut run_is_fg = false; // first run is always bg (pixel 0 == bg)

    for &px in display.iter().rev().skip(1) {
        let is_fg = px != bg;
        if is_fg == run_is_fg {
            run_len += 1;
        } else {
            hash = fnv_mix(hash, run_len as u8);
            hash = fnv_mix(hash, (run_len >> 8) as u8);
            run_len = 1;
            run_is_fg = is_fg;
        }
    }
    hash = fnv_mix(hash, run_len as u8);
    hash = fnv_mix(hash, (run_len >> 8) as u8);

    (hash, mask)
}
